<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * VisitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitRepository extends EntityRepository
{
    public function getDAU($dateFrom,$dateTo)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT date(v.visitedOn) as dates, COUNT( DISTINCT v.user ) as dau FROM  AppBundle:Visit v WHERE v.visitedOn BETWEEN  ?1 AND  ?2 group by dates'
            )->setParameters([1=>$dateFrom,2=>$dateTo])
            ->getResult();
    }
}
